### ISSUE TITLE
KeyError: 'C:\\dev\\disk\\by-uuid\\BAC5375B

### ISSUE THREAD

**Issue by Kuki77** [Philipp91/picasa2digikam#1]
Hi,
I just tried to test your tool, but:

c:\Programme_Manuell\_GRAFIK\picasa2digikam-main>python  .\main.py --dry_run --photos_dir "x:\Dokumente\Fotos 2011" --digikam_db="C:\Users\Martin\Pictures\digiKam\digikam4.db" -v
INFO: Inspecting existing digiKam database
Traceback (most recent call last):
  File "c:\Programme_Manuell\_GRAFIK\picasa2digikam-main\main.py", line 57, in <module>
    main()
  File "c:\Programme_Manuell\_GRAFIK\picasa2digikam-main\main.py", line 45, in main
    db = digikam_db.DigikamDb(args.digikam_db)
  File "c:\Programme_Manuell\_GRAFIK\picasa2digikam-main\digikam_db.py", line 43, in __init__
    for mountpoint in dev_to_mountpoints[dev]:
KeyError: 'C:\\dev\\disk\\by-uuid\\BAC5375B'

Any hint about this keyerror?

**Comment by Philipp91** [comment]
You're basically running into [this TODO](https://github.com/Philipp91/picasa2digikam/blob/79b404ff45b8541f8228df4efb2c3b3fdc631030/digikam_db.py#L39). But don't worry, it shouldn't be hard to fix and I just left it unimplemented because I couldn't have tested it properly.

Here's how you can go about properly implementing this (I'd appreciate a PR):
1. Dump the contents of `dev_to_mountpoints` in order to find what the valid keys are. For instance, insert `logging.info(sdiskpart.device)` at line 30, or `logging.info(dev_to_mountpoints)` at line 32 (not sure if the latter properly prints all the keys -- you'll see).
2. Dump all the `identifier`s without making the program crash. For instance, insert `logging.info(identifier + ' ' + specificPath)` at line 35 and delete the remainder of the loop (up to line 44).
3. Decide which of the `identifier`s is the right one and let's figure out a way to map this one to a `dev_to_mountpoints` key without skipping the other ones (if any). Depending on your programming skills, you can do this by yourself, but feel free to post the outputs you got for the steps above.

**Comment by Kuki77** [comment]
Hi Philipp,

I think part 3 will be to complicated for me, but I'll try it.

Would another workaround be to try it from a Linux LiveCD (or Linux in a VM) for example? Or how have you done it? In the "Suggested usage" you're also using Windows paths (C:\...).

**Comment by Kuki77** [comment]
OK, here we are (and I hope, I've done steps 1 and 2 the right way):

My part of the code (the two lines with #MK):

        dev_to_mountpoints: Dict[str, Set[str]] = {}
        for sdiskpart in psutil.disk_partitions():
            logging.info(sdiskpart.device) #MK
            dev_to_mountpoints.setdefault(sdiskpart.device, set()).add(sdiskpart.mountpoint)

        self.album_roots = {}
        for row in self.conn.cursor().execute('SELECT id, type, identifier, specificPath FROM AlbumRoots WHERE status = 0'):
            id, type, identifier, specificPath = row
            logging.info(identifier + ' ' + specificPath) #MK
            if type != 1:
                continue  # Skip all that aren't local disks.

From "assert ..." till ..." specificPath] = id" then commented out.

And this is the output:

c:\Programme_Manuell\_GRAFIK\picasa2digikam-main>python  .\main.py --dry_run --photos_dir "X:\Dokumente\Fotos 2011" --digikam_db="C:\Users\Martin\Pictures\digiKam\digikam4.db" -v
INFO: Inspecting existing digiKam database
INFO: C:\
INFO: X:\
INFO: Y:\
INFO: volumeid:?uuid=bac5375b /Users/Martin/Pictures/digiKam
INFO: volumeid:?uuid=e9dec1b0 /Dokumente/Fotos 2011
INFO: DigikamDb(file=WindowsPath('C:/Users/Martin/Pictures/digiKam/digikam4.db'), conn=<sqlite3.Connection object at 0x000001AB6E9A0F40>, album_roots={}, person_root_tag=4, internal_tags_id=1, pick_tags=[25, 24, 23, 22], star_tag=25)
INFO: Traversing input directories
INFO: ===========================================================================================
INFO: Now migrating X:\Dokumente\Fotos 2011\2011-01-01
Traceback (most recent call last):
  File "c:\Programme_Manuell\_GRAFIK\picasa2digikam-main\main.py", line 57, in <module>
    main()
  File "c:\Programme_Manuell\_GRAFIK\picasa2digikam-main\main.py", line 50, in main
    migrator.migrate_directories_under(input_root_dir=args.photos_dir, db=db, dry_run=args.dry_run)
  File "c:\Programme_Manuell\_GRAFIK\picasa2digikam-main\migrator.py", line 31, in migrate_directories_under
    contact_tags_per_dir[dir] = migrate_directory(dir, files, db, contact_tags_per_dir, dry_run=dry_run)
  File "c:\Programme_Manuell\_GRAFIK\picasa2digikam-main\migrator.py", line 47, in migrate_directory
    album_id = db.find_album_by_dir(input_dir)
  File "c:\Programme_Manuell\_GRAFIK\picasa2digikam-main\digikam_db.py", line 78, in find_album_by_dir
    raise ValueError('No digiKam AlbumRoot found for %s, only have %s' % (path, self.album_roots))
ValueError: No digiKam AlbumRoot found for X:\Dokumente\Fotos 2011\2011-01-01, only have {}

**Comment by Philipp91** [comment]
> Or how have you done it?

I polished this tool on Linux because I migrated to that (which is why I needed to get rid of Picasa in the first place). But I had started on Windows with WSL, which is the alternative that you could try.

> INFO: volumeid:?uuid=e9dec1b0 /Dokumente/Fotos 2011

This is tricky. We need to map `e9dec1b0` to `X:` somehow. But the `psutil.disk_partitions()` aren't useful on Windows because, as the [documentation](psutil.disk_partitions()) says, it only has the drive letter name and nothing else. And we can't do the `realpath /dev/disk/by-uuid/...` trick like on Linux either.

You could use [SQLite browser](https://sqlitebrowser.org/) to open up your database file manually and look into the AlbumRoots table (and perhaps nearby tables) to see if the `X:` is flying around there somewhere.

**Comment by Philipp91** [comment]
You could just hard-code sth like `self.album_roots = {'X:': 1}` where the `1` is the `AlbumRoots.id` from SQLite. We could also start supporting `volumeid:?path=C:\`, which should be supported (though not favored) by digiKam.

**Comment by Kuki77** [comment]
Way 1:
OK, I'll give WSL a try. But it'll take a while for installing everything necessary, I suppose.

Way 2:
Meanwhile here the results of SELECT * FROM AlbumRoots;

1	digiKam	0	1	volumeid:?uuid=bac5375b	/Users/Martin/Pictures/digiKam
2	Fotos 2011	0	2	volumeid:?uuid=e9dec1b0	/Dokumente/Fotos 2011

So, the 1 is the standard local digiKam pictures folder (as it's a fresh install, it's empty.
The 2 is one of my picture folders on drive X: (an USB HDD).
Later, if it work's for the "Fotos 2011" folder, I'd like to try a migration for the (much bigger) other folders too.

So, how to proceed now?

**Comment by Philipp91** [comment]
@mqualmann By any chance do you know how to map digiKam's UUIDs to drive letters on Windows?

// EDIT: Nevermind, found that digiKam uses Solid, and its Windows implementation [hex-formats the serial number](https://invent.kde.org/frameworks/solid/-/blob/master/src/solid/devices/backends/win/winstoragevolume.cpp#L57). This is unusual because most Windows tooling uses decimal format, but knowing this now, it's not a big problem to do the conversion.

**Comment by Philipp91** [comment]
@Kuki77 Please try this patch: https://github.com/Philipp91/picasa2digikam/pull/2/files

**Comment by Kuki77** [comment]
@Philipp91 
OK, I'll try the patch.

Till now I tried to get it to work under WSL. But this was the meanwhile result:

kuki@AcerA515:~/picasa2digikam-main$ python3  ./main.py --dry_run --photos_dir "/mnt/x/Dokumente/Fotos 2011" --digikam_db="/mnt/c/users/Martin/Pictures/digiKam/digikam4.db"
Traceback (most recent call last):
  File "./main.py", line 57, in <module>
    main()
  File "./main.py", line 45, in main
    db = digikam_db.DigikamDb(args.digikam_db)
  File "/home/kuki/picasa2digikam-main/digikam_db.py", line 43, in __init__
    for mountpoint in dev_to_mountpoints[dev]:
KeyError: '/dev/disk/by-uuid/BAC5375B'

**Comment by Kuki77** [comment]
And here the result of the test with the patch:

c:\Programme_Manuell\_GRAFIK\picasa2digikam-main>python  .\main.py --dry_run --photos_dir "X:\Dokumente\Fotos 2011" --digikam_db="C:\Users\Martin\Pictures\digiKam\digikam4.db"
Traceback (most recent call last):
  File "c:\Programme_Manuell\_GRAFIK\picasa2digikam-main\main.py", line 57, in <module>
    main()
  File "c:\Programme_Manuell\_GRAFIK\picasa2digikam-main\main.py", line 45, in main
    db = digikam_db.DigikamDb(args.digikam_db)
  File "c:\Programme_Manuell\_GRAFIK\picasa2digikam-main\digikam_db.py", line 34, in __init__
    def volume_uuid_to_mountpoints(uuid: str) -> Set[str]:
NameError: name 'Set' is not defined. Did you mean: 'set'?

After changing all occurences of "Set[str]" to "set[str]" and rerunning:

c:\Programme_Manuell\_GRAFIK\picasa2digikam-main>python  .\main.py --dry_run --photos_dir "X:\Dokumente\Fotos 2011" --digikam_db="C:\Users\Martin\Pictures\digiKam\digikam4.db"
Traceback (most recent call last):
  File "c:\Programme_Manuell\_GRAFIK\picasa2digikam-main\main.py", line 57, in <module>
    main()
  File "c:\Programme_Manuell\_GRAFIK\picasa2digikam-main\main.py", line 45, in main
    db = digikam_db.DigikamDb(args.digikam_db)
  File "c:\Programme_Manuell\_GRAFIK\picasa2digikam-main\digikam_db.py", line 54, in __init__
    for mountpoint in volume_uuid_to_mountpoints(identifier[15:]):
  File "c:\Programme_Manuell\_GRAFIK\picasa2digikam-main\digikam_db.py", line 37, in volume_uuid_to_mountpoints
    return serial_to_mountpoints[int(uuid, 16)]
KeyError: 3133486939

**Comment by Philipp91** [comment]
If you just run `python` on the command line and then this in the interactive Python shell:

```python
import win32api
win32api.GetVolumeInformation("C:\\")
```

What do you get? In particular, is the serial number (in the second place of the output) the number 3133486939 or sth else?

**Comment by Philipp91** [comment]
> KeyError: '/dev/disk/by-uuid/BAC5375B'

On WSL, what does `ls /dev/disk/by-uuid/` give you?

**Comment by Kuki77** [comment]
Sorry for delay (work).

Answer 1:

>>> import win32api
>>> win32api.GetVolumeInformation("C:\\")
('', -1161480357, 255, 29820639, 'NTFS')


Answer 2:
kuki@AcerA515:~$ ls /dev/disk/by-uuid/
ls: cannot access '/dev/disk/by-uuid/': No such file or directory

Means, there is no /dev/disk

**Comment by Philipp91** [comment]
> -1161480357

Ok so the serial number is a signed int. I've added a conversion in #2, please try again.

> ls: cannot access '/dev/disk/by-uuid/': No such file or directory

Ok. And does that same snippet above with `import win32api` work under WSL? I'd be surprised, but if it doesn't, then that would mean that WSL is neither like Linux nor like Windows enough to reuse the respective solutions, and we'd just leave WSL unsupported for now.

**Comment by Kuki77** [comment]
OK, here the test with the new version (#2) under Windows. It looks better, but still not successful.

c:\Programme_Manuell\_GRAFIK\picasa2digikam-main>python  .\main.py --dry_run --photos_dir "X:\Dokumente\Fotos 2011" --digikam_db="C:\Users\Martin\Pictures\digiKam\digikam4.db" -v
INFO: Inspecting existing digiKam database
INFO: DigikamDb(file=WindowsPath('C:/Users/Martin/Pictures/digiKam/digikam4.db'), conn=<sqlite3.Connection object at 0x0000016B74CEAD40>, album_roots={WindowsPath('C:/Users/Martin/Pictures/digiKam'): 1}, person_root_tag=4, internal_tags_id=1, pick_tags=[25, 24, 23, 22], star_tag=25)
INFO: Traversing input directories
INFO: ===========================================================================================
INFO: Now migrating X:\Dokumente\Fotos 2011\2011-01-01
Traceback (most recent call last):
  File "c:\Programme_Manuell\_GRAFIK\picasa2digikam-main\main.py", line 57, in <module>
    main()
  File "c:\Programme_Manuell\_GRAFIK\picasa2digikam-main\main.py", line 50, in main
    migrator.migrate_directories_under(input_root_dir=args.photos_dir, db=db, dry_run=args.dry_run)
  File "c:\Programme_Manuell\_GRAFIK\picasa2digikam-main\migrator.py", line 31, in migrate_directories_under
    contact_tags_per_dir[dir] = migrate_directory(dir, files, db, contact_tags_per_dir, dry_run=dry_run)
  File "c:\Programme_Manuell\_GRAFIK\picasa2digikam-main\migrator.py", line 47, in migrate_directory
    album_id = db.find_album_by_dir(input_dir)
  File "c:\Programme_Manuell\_GRAFIK\picasa2digikam-main\digikam_db.py", line 89, in find_album_by_dir
    raise ValueError('No digiKam AlbumRoot found for %s, only have %s' % (path, self.album_roots))
ValueError: No digiKam AlbumRoot found for X:\Dokumente\Fotos 2011\2011-01-01, only have {WindowsPath('C:/Users/Martin/Pictures/digiKam'): 1}


And here the mentiones check in WSL (Ubuntu 20.04 LTS):

>>> import win32api
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'win32api'
>>> win32api.GetVolumeInformation("C:\")
  File "<stdin>", line 1
    win32api.GetVolumeInformation("C:\")
                                       ^
SyntaxError: EOL while scanning string literal

So I tried to install it, but:

kuki@AcerA515:~$ pip3 install pywin32
ERROR: Could not find a version that satisfies the requirement pywin32 (from versions: none)
ERROR: No matching distribution found for pywin32

**Comment by Philipp91** [comment]
Is your USB HDD plugged in, i.e. is `X:` really available?

**Comment by Kuki77** [comment]
Yes, of course.

Proof:
https://snipboard.io/ga2vWo.jpg
and also visible / usable in digiKam:
https://snipboard.io/Fc1S79.jpg
https://snipboard.io/FvH7Nk.jpg

**Comment by Philipp91** [comment]
I've uploaded a new version of the patch with more logging. Please send the
new log output.

Kuki77 ***@***.***> schrieb am Fr., 11. Feb. 2022, 07:17:

**Comment by Kuki77** [comment]
Here we are. It seems, it's skipping the album because it'S declared not to be on a local disk (see also my 2nd screenshot in previous post).

c:\Programme_Manuell\_GRAFIK\picasa2digikam-main>python  .\main.py --dry_run --photos_dir "X:\Dokumente\Fotos 2011" --digikam_db="C:\Users\Martin\Pictures\digiKam\digikam4.db" -v
INFO: Inspecting existing digiKam database
INFO: serial_to_mountpoints={3133486939: {'C:\\'}, 3923689904: {'X:\\'}, 305419896: {'Y:\\'}}
INFO: Skipping album 2 at /Dokumente/Fotos 2011 on volumeid:?uuid=e9dec1b0 because it is not a local disk
INFO: album_roots={WindowsPath('C:/Users/Martin/Pictures/digiKam'): 1}
INFO: DigikamDb(file=WindowsPath('C:/Users/Martin/Pictures/digiKam/digikam4.db'), conn=<sqlite3.Connection object at 0x000001FF32CF9040>, album_roots={WindowsPath('C:/Users/Martin/Pictures/digiKam'): 1}, person_root_tag=4, internal_tags_id=1, pick_tags=[25, 24, 23, 22], star_tag=25)
INFO: Traversing input directories
INFO: ===========================================================================================
INFO: Now migrating X:\Dokumente\Fotos 2011\2011-01-01
Traceback (most recent call last):
  File "c:\Programme_Manuell\_GRAFIK\picasa2digikam-main\main.py", line 57, in <module>
    main()
  File "c:\Programme_Manuell\_GRAFIK\picasa2digikam-main\main.py", line 50, in main
    migrator.migrate_directories_under(input_root_dir=args.photos_dir, db=db, dry_run=args.dry_run)
  File "c:\Programme_Manuell\_GRAFIK\picasa2digikam-main\migrator.py", line 31, in migrate_directories_under
    contact_tags_per_dir[dir] = migrate_directory(dir, files, db, contact_tags_per_dir, dry_run=dry_run)
  File "c:\Programme_Manuell\_GRAFIK\picasa2digikam-main\migrator.py", line 47, in migrate_directory
    album_id = db.find_album_by_dir(input_dir)
  File "c:\Programme_Manuell\_GRAFIK\picasa2digikam-main\digikam_db.py", line 93, in find_album_by_dir
    raise ValueError('No digiKam AlbumRoot found for %s, only have %s' % (path, self.album_roots))
ValueError: No digiKam AlbumRoot found for X:\Dokumente\Fotos 2011\2011-01-01, only have {WindowsPath('C:/Users/Martin/Pictures/digiKam'): 1}

**Comment by Philipp91** [comment]
Then log its type number and let's add it to the if condition.

Kuki77 ***@***.***> schrieb am Fr., 11. Feb. 2022, 08:44:

**Comment by Kuki77** [comment]
Hi, you are right. With this change in line 53 

            if type != 1 and  type != 2:


it's proceeding, but facing another issue with subfolders.
I have to obfuscate some information (XXX) due to privacy reasons.

Output:


c:\Programme_Manuell\_GRAFIK\picasa2digikam-main>python  .\main.py --dry_run --photos_dir "X:\Dokumente\Fotos 2011" --digikam_db="C:\Users\Martin\Pictures\digiKam\digikam4.db" -v
INFO: Inspecting existing digiKam database
INFO: serial_to_mountpoints={3133486939: {'C:\\'}, 3923689904: {'X:\\'}, 305419896: {'Y:\\'}}
INFO: album_roots={WindowsPath('C:/Users/Martin/Pictures/digiKam'): 1, WindowsPath('X:/Dokumente/Fotos 2011'): 2}
INFO: DigikamDb(file=WindowsPath('C:/Users/Martin/Pictures/digiKam/digikam4.db'), conn=<sqlite3.Connection object at 0x000002BA156EAD40>, album_roots={WindowsPath('C:/Users/Martin/Pictures/digiKam'): 1, WindowsPath('X:/Dokumente/Fotos 2011'): 2}, person_root_tag=4, internal_tags_id=1, pick_tags=[25, 24, 23, 22], star_tag=25)
INFO: Traversing input directories
INFO: ===========================================================================================
INFO: Now migrating X:\Dokumente\Fotos 2011\2011-01-01
INFO: Creating digiKam tag Picasa
INFO: Creating digiKam person tag XXX
INFO: ===========================================================================================
INFO: Now migrating X:\Dokumente\Fotos 2011\2011-01-02
INFO: Creating digiKam tag Picasa
INFO: Creating digiKam person tag XXX
INFO: Creating digiKam person tag XXX
INFO: ===========================================================================================
INFO: Now migrating X:\Dokumente\Fotos 2011\2011-01-02\HDR
Traceback (most recent call last):
  File "c:\Programme_Manuell\_GRAFIK\picasa2digikam-main\main.py", line 57, in <module>
    main()
  File "c:\Programme_Manuell\_GRAFIK\picasa2digikam-main\main.py", line 50, in main
    migrator.migrate_directories_under(input_root_dir=args.photos_dir, db=db, dry_run=args.dry_run)
  File "c:\Programme_Manuell\_GRAFIK\picasa2digikam-main\migrator.py", line 31, in migrate_directories_under
    contact_tags_per_dir[dir] = migrate_directory(dir, files, db, contact_tags_per_dir, dry_run=dry_run)
  File "c:\Programme_Manuell\_GRAFIK\picasa2digikam-main\migrator.py", line 47, in migrate_directory
    album_id = db.find_album_by_dir(input_dir)
  File "c:\Programme_Manuell\_GRAFIK\picasa2digikam-main\digikam_db.py", line 91, in find_album_by_dir
    raise ValueError('No digiKam Album found for %s (relative path %s) under root %s' % (path, relative_path, root_id))
ValueError: No digiKam Album found for X:\Dokumente\Fotos 2011\2011-01-02\HDR (relative path /2011-01-02\HDR) under root 2
