### ISSUE TITLE
[bug] star_tag AssertionError

### ISSUE THREAD

**Issue by doej1367** [Philipp91/picasa2digikam#22]
After a long fight to get python running on windows 10 with psutil [answer was to use the python installer from the windows store] I finally got the script to run after I converted it into a one-liner.

Now I encountered another problem - an assertion error with the star tags. Can anyone help me what that means and how I fix this? 
Note: It also doesn't change anything if it is a dry run or not.

Command (one-liner for copy-paste):
```
python main.py --photos_dir="L:\Users\User\Pictures" --digikam_db="L:\Users\User\Pictures\digikam4.db" --contacts="%LocalAppData%\Google\Picasa2\contacts\contacts.xml" -vv
```
Command (full console and multiple lines for readability):
```
PS C:\Users\User\Documents_SSD\picasa2digikam-main\picasa2digikam-main>
python main.py
--photos_dir="L:\Users\User\Pictures"
--digikam_db="L:\Users\User\Pictures\digikam4.db"
--contacts="%LocalAppData%\Google\Picasa2\contacts\contacts.xml"
-vv
```
Output:
```
INFO: Creating database backup at L:\Users\User\Pictures\digikam4.db.bak.1667309545
INFO: Inspecting existing digiKam database
DEBUG: file=L:\Users\User\Pictures\digikam4.db
WARNING: Cannot determine address of disk E:\ mounted at E:\, so it will be unavailable
WARNING: Cannot determine address of disk I:\ mounted at I:\, so it will be unavailable
WARNING: Cannot determine address of disk J:\ mounted at J:\, so it will be unavailable
DEBUG: serial_to_mountpoints={2485354110: {'C:\\'}, 1879958864: {'D:\\'}, 242647954: {'L:\\'}, 940141661: {'Z:\\'}}
DEBUG: id=1 specific_path=/Users/User/Pictures identifier=volumeid:?uuid=e768392
DEBUG: album_roots={WindowsPath('L:/Users/User/Pictures'): 1}
Traceback (most recent call last):
  File "C:\Users\User\Documents_SSD\picasa2digikam-main\picasa2digikam-main\main.py", line 66, in <module>
    main()
  File "C:\Users\User\Documents_SSD\picasa2digikam-main\picasa2digikam-main\main.py", line 51, in main
    db = digikam_db.DigikamDb(args.digikam_db)
  File "C:\Users\User\Documents_SSD\picasa2digikam-main\picasa2digikam-main\digikam_db.py", line 90, in __init__
    assert self.star_tag
AssertionError
```

**Comment by Philipp91** [comment]
```
self.star_tag = self.find_tag(self.internal_tags_id, 'Pick Label Accepted')
```

picasa2digikam converts Picasa stars to that "green flag" marker in digiKam. That is stored as like any other named tag, just that somehow the digiKam system knows to treat that tag specially, i.e. to display it as a green flag instead of just a tag name. As far as I had reverse-engineered, that tag could be found in the digiKam database under the name `"Pick Label Accepted"`. That doesn't seem to be the case here.

1. Does it work if you mark any photo in your digiKam database with that green flag, then close digiKam and retry? I could imagine that this tag is only created in the database once the feature is used for the first time.
2. If that doesn't help, could you please download the "DB Browser for SQLite", open up your digikam4.db with it, look into the `Tags` table and see which tags are there -- perhaps it has a different name on your system, e.g. different upper/lower casing or translated to another language.

**Comment by doej1367** [comment]
Thank you for the fast answer.
After I 'mark[ed] any photo in [my] digiKam database with that green flag' and 'open[ed] up [my] digikam4.db with [DB Browser for SQLite]', that error is now gone, but the program immidiatly stopped at the next one.

```
INFO: Inspecting existing digiKam database
DEBUG: file=L:\Users\User\Pictures\digikam4.db
WARNING: Cannot determine address of disk E:\ mounted at E:\, so it will be unavailable
WARNING: Cannot determine address of disk I:\ mounted at I:\, so it will be unavailable
WARNING: Cannot determine address of disk J:\ mounted at J:\, so it will be unavailable
DEBUG: serial_to_mountpoints={2485354110: {'C:\\'}, 1879958864: {'D:\\'}, 242647954: {'L:\\'}, 940141661: {'Z:\\'}}
DEBUG: id=1 specific_path=/Users/User/Pictures identifier=volumeid:?uuid=e768392
DEBUG: album_roots={WindowsPath('L:/Users/User/Pictures'): 1}
DEBUG: DigikamDb(file=WindowsPath('L:/Users/User/Pictures/digikam4.db'), conn=<sqlite3.Connection object at 0x0000022B39E36C40>, album_roots={WindowsPath('L:/Users/User/Pictures'): 1}, person_root_tag=4, internal_tags_id=1, pick_tags=[21, 20, 19, 18], star_tag=21)
INFO: Traversing input directories
DEBUG: Reading contacts from %LocalAppData%\Google\Picasa2\contacts\contacts.xml
Traceback (most recent call last):
  File "C:\Users\User\Documents_SSD\picasa2digikam-main\picasa2digikam-main\main.py", line 66, in <module>
    main()
  File "C:\Users\User\Documents_SSD\picasa2digikam-main\picasa2digikam-main\main.py", line 56, in main
    migrator.migrate_directories_under(input_root_dir=args.photos_dir, db=db,
  File "C:\Users\User\Documents_SSD\picasa2digikam-main\picasa2digikam-main\migrator.py", line 72, in migrate_directories_under
    tree = ET.parse(contacts_file)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\xml\etree\ElementTree.py", line 1222, in parse
    tree.parse(source, parser)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\xml\etree\ElementTree.py", line 569, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '%LocalAppData%\\Google\\Picasa2\\contacts\\contacts.xml'
```

It now sais it can't find the ´contacts.xml´ file even though it exists exactly where it expects it to be...

**Comment by Philipp91** [comment]
I don't think it understands that `%LocalAppData%` placeholder. This would normally be substituted by the shell before passing it to Python, but perhaps the one you're using doesn't do it. I suggest you figure out the real path (just put that placeholder into Windows Explorer and see where it takes you) and then specify a real path like `L:\...` or `C:\...` instead. If that fixes things, feel free to send an update for this repo's readme to replace the placeholder there too.

**Comment by doej1367** [comment]
> Perhaps the [shell] you're using doesn't [substitute the `%LocalAppData%` placeholder]

That'd be Visual Studio Code then - it also had problems with the multiline command 'layout' so It could very well be.

EDIT:

Ok, at least it quickly ran through once without errors.

Next stop was this thing here...
```
DEBUG: self_contact_to_tag={}
DEBUG: Adding album 396ffbbfd73767475307905d8f760c04 to image 1008 (20130904114744(1).jpg)
Traceback (most recent call last):
  File "C:\Users\User\Documents_SSD\picasa2digikam-main\picasa2digikam-main\main.py", line 66, in <module>
    main()
  File "C:\Users\User\Documents_SSD\picasa2digikam-main\picasa2digikam-main\main.py", line 56, in main
    migrator.migrate_directories_under(input_root_dir=args.photos_dir, db=db,
  File "C:\Users\User\Documents_SSD\picasa2digikam-main\picasa2digikam-main\migrator.py", line 107, in migrate_directories_under
    contact_tags_per_dir[dir] = migrate_directory(dir, files, db,
  File "C:\Users\User\Documents_SSD\picasa2digikam-main\picasa2digikam-main\migrator.py", line 175, in migrate_directory
    raise ValueError(f'digiKam does not know {(input_dir / filename)}')
ValueError: digiKam does not know L:\Users\User\Pictures\...<cencored for privacy reasons>.JPG
```
For now I'm gonna wait for digiKam to import that TB of pictures... Then I'ma try and run it again as I think it might need the pictures added in some capacity to know what to do with the data to be imported... `do NOT add your photos yet` probably gonna cause more problems than it fixes but yea...
