### ISSUE TITLE
Python SQLite Operationalerror: unable to open database file Windows 11

### ISSUE THREAD

**Issue by gc407** [Philipp91/picasa2digikam#23]
Hello, I am fairly new at Python and programming in general. I have searched for a resolution but nothing so far. This is driving me crazy.

This program writes to the database and csv file just fine on the Mac. But when I try running it on Win11, I get the error. 
OS: Win 11
Python 3.11
This runs when I click a button (Tkinter) and it calls Grab_Manifest(), which is here. The error occurs at the con=sql.connect() part:

def Grab_Manifest():

    start1 = sb_inp.get()

    con = sql.connect("streat.db")
    cur = con.cursor()

    cur.execute('SELECT lastname, firstname, MI, DODID, Volume, Type, BoxNum FROM Patients WHERE BoxNum = (?)', (start1,))
    
    with open("Manifest.csv", "wb") as csv_file:
        csv_writer = csv.writer(csv_file, delimiter="\t")
        csv_writer.writerow([i[0].encode('utf-8') for i in cur.description])
        #csv_writer.writerow([i[0] for i in cur.description(start, end)])
        csv_writer.writerows(cur)
 
    con.close

----------
The error:

**Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.240.0_x64__qbz5n2kfra8p0\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Streat\StreatApp.py", line 704, in commit_form
    Grab_Manifest()
  File "C:\Streat\StreatApp.py", line 148, in Grab_Manifest
    con = sql.connect("streat.db")
          ^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: unable to open database file**

I can open the db in a browser. I have verified the path is correct and the file is there (opened with db browser). Is this perhaps a permission thing? Like I said, works like a charm on my Mac. I am 2 days into this and I need it fixed for a work project ASAP! Thank you! I am a NEWBIE.

**Comment by Philipp91** [comment]
This seems unrelated to picasa2digikam. Perhaps StackOverflow is a better place to ask such a question.
