### ISSUE TITLE
Question about albums

### ISSUE THREAD

**Issue by celmi** [Philipp91/picasa2digikam#27]
I'm about to follow the procedure... but hesitate, because I don't understand how albums from Picasa are going to be found by this script... In step 5 of the "suggested usage" there's a parameter for the contacts.xml. But where's the parameter for album-information? 

Or did I misundertand Point two of "supported metadata" section about the albums? Do I not need to run this script to import Picasa-albums at all?

Many thanks for your help.

**Comment by Philipp91** [comment]
In every directory you have today, there's a (possibly hidden) `picasa.ini` file that contains the album information. Feel free to look inside with a text editor. [Here](https://github.com/Philipp91/picasa2digikam/blob/a22a696217af80aa7972004fc895ac859a7efb78/migrator.py#L144) is where the script reads that and maps it to digiKam tags.
