### ISSUE TITLE
Dry-Run Error: AttributeError: module 'argparse' has no attribute 'BooleanOptionalAction'

### ISSUE THREAD

**Issue by celmi** [Philipp91/picasa2digikam#28]
Upon my dry run on a Win10 PC I am getting this error: 

``
C:\picasa2digikam-main>python main.py --dry_run --photos_dir="C:\Users\MCH\_Daten_MCH\Fotosammlung" --digikam_db="C:\Users\MCH\_Daten_MCH\Fotosammlung_Datenbank\Digikam_DB\digikam4.db" --contacts="%LocalAppData%\Google\Picasa2\contacts\contacts.xml"
Traceback (most recent call last):
  File "main.py", line 66, in <module>
    main()
  File "main.py", line 41, in main
    parser = init_argparse()
  File "main.py", line 27, in init_argparse
    parser.add_argument('--skip_same_rect', action=argparse.BooleanOptionalAction,
AttributeError: module 'argparse' has no attribute 'BooleanOptionalAction'
``

Any idea what I might have done wrong? Many thanks in advance!!!

**Comment by Philipp91** [comment]
https://docs.python.org/3/library/argparse.html says "Added in version 3.9." for BooleanOptionalAction. So you need to update your Python version.
