### ISSUE TITLE
Dry-run Error: ValueError: invalid literal for int() with base 16

### ISSUE THREAD

**Issue by celmi** [Philipp91/picasa2digikam#29]
Ok, two steps ahead, now this error awaits me:

> C:\picasa2digikam-main>py -3.12-64 main.py --dry_run --photos_dir="C:\Users\MCH\_Daten_MCH\Fotosammlung" --digikam_db="C:\Users\MCH\_Daten_MCH\Fotosammlung_Datenbank\Digikam_DB\digikam4.db" --contacts="%LocalAppData%\Google\Picasa2\contacts\contacts.xml"
> Traceback (most recent call last):
>   File "C:\picasa2digikam-main\main.py", line 66, in <module>
>     main()
>   File "C:\picasa2digikam-main\main.py", line 51, in main
>     db = digikam_db.DigikamDb(args.digikam_db)
>          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\picasa2digikam-main\digikam_db.py", line 73, in __init__
>     for mountpoint in volume_uuid_to_mountpoints(identifier[15:]):
>                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\picasa2digikam-main\digikam_db.py", line 49, in volume_uuid_to_mountpoints
>     return serial_to_mountpoints[int(uuid, 16)]
>                                  ^^^^^^^^^^^^^
> ValueError: invalid literal for int() with base 16: 'd22086d1&fileuuid=96d8af24-49c9-4b2f-9402-54f7358ab5a7'

Can you help me once more figuring out, what's going on?
Many thanks in advance!

**Comment by Philipp91** [comment]
Please rerun with `-vv` and send me the output of the log line that starts with `serial_to_mountpoints=`.

**Comment by celmi** [comment]
Your support is amazingly fast. Thank you!

> INFO: Inspecting existing digiKam database
DEBUG: file=C:\Users\MCH\_Daten_MCH\Fotosammlung_Datenbank\Digikam_DB\digikam4.db
**DEBUG: serial_to_mountpoints={3525347025: {'C:\\'}, 1252787276: {'D:\\'}}**
DEBUG: id=1 specific_path=/Users/MCH/_Daten_MCH/Fotosammlung identifier=volumeid:?uuid=d22086d1&fileuuid=96d8af24-49c9-4b2f-9402-54f7358ab5a7

**Comment by Philipp91** [comment]
d22086d1 in hex is 3525347025 and I assume your photos are indeed on `C:\`.

Try this patch: https://github.com/Philipp91/picasa2digikam/pull/30/files

It's a one-line change. You can just open that file and apply the edit manually, then save and retry.

**Comment by celmi** [comment]
Did as you told, worked like a charm :-) 👍
