### ISSUE TITLE
KeyError from contact_to_tag

### ISSUE THREAD

**Issue by Philipp91** [Philipp91/picasa2digikam#5]
```
Traceback (most recent call last):
  File "c:\Programme_Manuell\_GRAFIK\picasa2digikam-main\migrator.py", line 78, in migrate_directory
    migrate_file(filename, image_id, ini_section, db, album_to_tag, contact_to_tag, dry_run=dry_run)
  File "c:\Programme_Manuell\_GRAFIK\picasa2digikam-main\migrator.py", line 129, in migrate_file
    migrate_face(image_id, filename, face_data, db, contact_to_tag, dry_run=dry_run)
  File "c:\Programme_Manuell\_GRAFIK\picasa2digikam-main\migrator.py", line 142, in migrate_face
    tag_id = contact_to_tag[contact_id]
KeyError: '806702b3339676ef'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Programme_Manuell\_GRAFIK\picasa2digikam-main\main.py", line 57, in <module>
    main()
  File "c:\Programme_Manuell\_GRAFIK\picasa2digikam-main\main.py", line 50, in main
    migrator.migrate_directories_under(input_root_dir=args.photos_dir, db=db, dry_run=args.dry_run)
  File "c:\Programme_Manuell\_GRAFIK\picasa2digikam-main\migrator.py", line 31, in migrate_directories_under
    contact_tags_per_dir[dir] = migrate_directory(dir, files, db, contact_tags_per_dir, dry_run=dry_run)
  File "c:\Programme_Manuell\_GRAFIK\picasa2digikam-main\migrator.py", line 80, in migrate_directory
    raise RuntimeError('Error when processing %s/%s' % (input_dir, filename)) from e
RuntimeError: Error when processing X:\Dokumente\Fotos 2011\2011-01-15/DSC00436.JPG
```

_Originally posted by @Kuki77 in https://github.com/Philipp91/picasa2digikam/issues/4#issuecomment-1036515566_

**Comment by Philipp91** [comment]
Please see the explanation added in #6. If it's a common problem, a command line flag could be added to automatically drop all such face tags. For my photo collection, I found it easier to add the missing contacts to the affected ini files manually, thereby not losing any information.

**Comment by Kuki77** [comment]
Hi!
I've read the explanation in #6, but I must confess, that I don't understand what's the best way to proceed. 
I have here a sum of ~ 125,000 pictures in ~ 2,300 folders/subfolders from the past 20 years or more. 
A manual cleansing of the ini files is not possible.

So is it possible to have an additional parameter to get such pictures listed (in test mode) and the corresponding faces tags deleted (in "real" mode; perhaps as another additonal parameter)?!

**Comment by Philipp91** [comment]
Ok. Seeing as there are already other places where a warning is emitted when data is dropped, I've just made it a warning without a parameter. The readme already says "take a look at relevant-looking warnings". That should also allow people who _want_ to fix these warnings to do so more quickly (without having to rerun for each fixed warning, but instead going over the logs all at once).

See #7

**Comment by Kuki77** [comment]
This means, these single faces tags get lost, but at least the program proceeds?
How about an output to a text files for such a log entries?

I really started to fix these ini-files one by one when the py-program interrupts.
There are two ways:
1. Start Picasa and find the mentioned picture. Change the the face tag in Picasa (to a wrong person) and retag it again to thre right one.
2. Edit the ini-file in a text editor and add the missing person / face information in the [Contacts2] section (or create the section if it's completely missing).

But it's "suspicious" that Picasa itself is not affecting any issues with this missing informaion (but I suppose, it's just ignoring the ini-files and is relying on it's own database).

**Comment by Philipp91** [comment]
Writing output to a file is a core functionality of your shell:

```
./main.py .... --dry_run > outputfile.txt
```

If you want only those lines, do sth like:

```
type outputfile.txt | findstr "Dropping face" > droppedfaces.txt
```

**Comment by Kuki77** [comment]
OK, thanks. I know the > functionality. But the type ... tip is good. Thanks!

BTW
I editet / expanded my post above.

**Comment by Philipp91** [comment]
> I suppose, it's just ignoring the ini-files and is relying on it's own database

That's exactly right. I recall some function in Picasa to flush data from the database to disk, but sadly that writes to EXIF tags and not to the .picasa.ini file. Somehow Picasa assumes that the ini file is always up to date. It wasn't designed for people manually moving things around in the file system, synchronizing with other machines, external drives, etc.

**Comment by Kuki77** [comment]
OK, I think, this way it will work (for me). 
In my 2011 folder I have ~16,500 files in ~170 folders.
~700 pictures are mentioned, that the faces have been dropped.

Any idea, how to get (in the findstr tip from you side) also the corresponding current path from which the files are "dropped" (means also the lines starting with "INFO: Now migrating  ....")?!

I've found one ini file, which was corrupt, I had to delete it completely.
And three ini-files, in which the script found duplicate entries. 
In this case I moved the folders away and imported them into Picasa again for redo the face recognition. Any other tries to get Picasa to rewrite the ini files again have not succeeded. 

In the next days and weeks I'll try to clean up the other folders too and then, some day, migrate to digiKam

Thank you again! Great work! And thanks for your amazing support!

(this issue may be closed).

**Comment by Philipp91** [comment]
> Any idea, how to get (in the findstr tip from you side) also the corresponding current path from which the files are "dropped" (means also the lines starting with "INFO: Now migrating ....")?!

How about:

```
type outputfile.txt | findstr "Now migrationg|Dropping face" > droppedfaces.txt
```
